#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
title:  Jingyun Jia
about: aboutme

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
    - GitHub Pages: "https://pages.github.com/"
  Author's home: "http://deanattali.com"

social-network-links:
  rss: true
  email: "someone@example.com"
  facebook: daattali
  github: daattali
  twitter: daattali


